---
# Деплой 
- name: Install Suricata
  hosts: servers
  gather_facts: false #пока не понятно нужен ли данный параметр

  vars:
    IFACE: vlan492
    proxy_env:
      http_proxy: http://proxy:3128
      https_proxy: http://proxy:3128

  tasks:
    - name: Add suricata stable repository from PPA and install its signing key on Ubuntu target
      ansible.builtin.apt_repository:
        repo: ppa:oisf/suricata-stable

    - name: Install required packages
      apt:
        name: suricata
        state: latest
      #environment: "{{ proxy_env }}"
      
    - name: Change /etc/default/suricata
      lineinfile:
        dest: /etc/default/suricata
        regexp: IFACE
        line: IFACE={{ IFACE }}
  
    - name: Copy suricata conf
      copy:
        src: etc/suricata/suricata.yaml.j2
        dest: /etc/suricata/suricata.yaml
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: Change /etc/suricata/suricata.yaml #here now
        lineinfile:
          dest: /etc/default/suricata
          regexp: IFACE
          line: IFACE={{ IFACE }}

    - name: Logrotate.d conf
      template:
        src: etc/logrotate.d/suricata.j2
        dest: etc/logrotate.d/suricata
        owner: root
        group: root
        mode: 0640
        backup: no
    
    - name: Update suricata rules
      ansible.builtin.command:
        cmd: suricata-update

    - name: Enable service suricata
      ansible.builtin.systemd:
        name: suricata
        enabled: yes
        masked: no

    - name: Start service suricata
      ansible.builtin.systemd:
        state: started
        name: suricata

# Управление сервисом сурикаты
- name: Services Suricata
  hosts: servers
  gather_facts: false 

  tasks:

    - name: Start service suricata
      ansible.builtin.systemd:
        state: started
        name: suricata

    - name: Stopped service suricata
      ansible.builtin.systemd:
        state: stopped
        name: suricata

    - name: Restart service suricata
      ansible.builtin.systemd:
        state: restarted
        name: suricata