---

- name: Install Suricata
  hosts: servers
  gather_facts: false

  vars:
    IFACE: vlan999
    proxy_env:
      http_proxy: http://proxy:3128
      https_proxy: http://proxy:3128

  vars_files:
    - etc/vars/vars.yml

  tasks:
    - name: Add suricata stable repository from PPA and install its signing key on Ubuntu target
      ansible.builtin.apt_repository:
        repo: ppa:oisf/suricata-stable

    - name: Install required packages
      apt:
        name: suricata
        state: latest
      environment: "{{ proxy_env }}"
      
    - name: Change /etc/default/suricata
      lineinfile:
        dest: /etc/default/suricata
        regexp: IFACE
        line: IFACE={{ IFACE }}
  
    - name: Copy suricata conf
      copy:
        src: etc/suricata/suricata.yaml.j2
        dest: /etc/suricata/suricata.yaml
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: Logrotate.d conf
      template:
        src: etc/logrotate.d/suricata.j2
        dest: /etc/logrotate.d/suricata
        owner: root
        group: root
        mode: 0644
        backup: no
    
    - name: Update suricata rules
      command: suricata-update

    - name: Add rules for surricata from PT
      command: suricata-update enable-source ptresearch/attackdetection

    - name: Add rules for surricata from Oisf
      command: suricata-update enable-source oisf/trafficid

    - name: Add rules for surricata from SSL-blacklist
      command: suricata-update enable-source sslbl/ssl-fp-blacklist

    - name: Enable service suricata
      ansible.builtin.systemd:
        name: suricata
        enabled: yes
        masked: no

    - name: Start service suricata
      ansible.builtin.systemd:
        state: started
        name: suricata